### ISSUE TITLE
Add wearable hats/masks

### ISSUE THREAD

**Issue by gb2dev** [gb2dev/HLA-NoVR#178]

**Comment by WynandSmall19** [comment]
![Capture](https://github.com/bfeber/HLA-NoVR/assets/135338757/f79ee337-f6bb-452b-b89f-c5ecd7787324)
![Capture 2](https://github.com/bfeber/HLA-NoVR/assets/135338757/49f3c48c-f089-45a5-8dec-5d855df34fb5)

Good day, I would just like to confirm if wearable hats and masks are still being worked on.

I see with the latest update from the 28th Dec, I can equip hats (if it wasn't available before), but I cannot equip any **masks**. I can simply pick them up and drop them again (See screenshots attached).

Apologies as I'm not sure based on your Github and Mod DB pages if this feature was fully released as I only saw the latest YouTube video that it is "Coming Soon". I take it this is still the case.

**Comment by gb2dev** [comment]
Added
