### ISSUE TITLE
Bug - Iron sight is bugged (Details in the post)

### ISSUE THREAD

**Issue by screenreel** [gb2dev/HLA-NoVR#228]
1. I'm getting two positions for the iron sight and it's random (See the screenshots/video).
2. Transition speed between weapons regular and iron sight position is slow. Feels bad when you are in combat.
3. After I cancel the iron sight position, I'm getting different FOV for a second and then it jumps to the proper FOV (See the video).
4. Reflex sight not works for some enemies (not showing the weak points)

https://youtu.be/zDOKbpMayvg

![1](https://github.com/bfeber/HLA-NoVR/assets/70162227/6481ba6e-ef9b-4256-95f1-bdbf8cfe447c)

![2](https://github.com/bfeber/HLA-NoVR/assets/70162227/071060b5-c854-47c3-9553-91196f1fbe52)

**Comment by bfeber** [comment]
Actually, Position 2 is correct. ADS should have zoom

**Comment by screenreel** [comment]
Alright makes sense

**Comment by gb2dev** [comment]
Fixed
