### ISSUE TITLE
Jeff Banging Against Invisible Door - Fridge Toner Puzzle Section

### ISSUE THREAD

**Issue by WynandSmall19** [gb2dev/HLA-NoVR#235]
Good day,

There is an issue at the beginning of the Jeff chapter just before entering the elevator where at the start of the toner puzzle in the fridge (just after Jeff bangs the door open when trapping him inside in order to complete the toner puzzle inside), where **Jeff bangs against an invisible door/wall/object** and he remains stuck this way even if you make additional noises to get him to move.

One can throw ANY object in ANY direction, he will continue to remain in this position which requires one to close/open the whole game again. But then this position needs to be avoided when trying to complete the toner puzzle inside the fridge, otherwise he gets stuck all over again in the same position as in the screenshot:
![20240216143337_1](https://github.com/bfeber/HLA-NoVR/assets/135338757/ed0d4fab-34fd-4313-bfa7-f8420a68245e)

One can get past this position by completing the toner puzzle inside in total silence, but this is obviously a glitch. I playtested this cycle over and over again coming down to the same result.

**Comment by sgjohnson1981** [comment]
I have this issue as well. I couldn't get him to move so I thought I'd just noclip through the wall but apparently he needs to get in the elevator with you, at least according to the walkthroughs. But he won't move regardless, so he can't get in the elevator. The elevator goes up so I just had to noclip my way up there.

**Comment by WynandSmall19** [comment]
That's correct. Jeff needs to be in the elevator with you, otherwise the level will not advance. The level will also not advance beyond this point if you don't complete the toner puzzle located within the freezer. So you're pretty much screwed if you attempt to solve the puzzle and make a noise, because Jeff will come charging towards the freezer and this is where he gets stuck in the doorway. The problem also persists if you have no saves before this point as reloading to a save after Jeff gets stuck does not "un-stuck" him if you know what I mean which means you'll have to start the level from scratch. The ONLY way to advance as mentioned is to complete the toner puzzle in total silence while Jeff is dangling around in the rest of the area and then moving toward the elevator to complete the rest of the level so that Jeff can move toward the elevator with you and then the game is pretty much bug free from there (albeit no other showstopper bugs as there are still a lot of other intermittent bugs in the game). This problem will not have been much of a pain if the toner puzzle were located elsewhere and the freezer could have been avoided altogether. The point is it's a bug nevertheless which have not occurred in prior builds of the No Vr release as I've played the game more times than I can count over the lifespan of this mod. The team needs to fix this as there is a collision glitch happening here.

**Comment by gb2dev** [comment]
Fixed
