### ISSUE TITLE
weapon issues,errors

### ISSUE THREAD

**Issue by eawej** [gb2dev/HLA-NoVR#244]
Yesterday its worked right,but today its all broken. I walk with error on my head,pistol doesent work (even the ammo counter),shotgun shots,and have a ammo counter,but it have no model,healt bar shows up numbers,not the hearts,wrist pockets shows brackets instead of items you have in it,chapters texts shows incorrect (example: WAJ12 AJMPOG225 MHKL4),if you have not enough resin and you try to make an unpgrade text is bugs like chapter text https://github.com/gb2dev/HLA-NoVR/assets/171096150/a56ebd9f-0c27-44c9-994c-c3232514b2ab
https://github.com/gb2dev/HLA-NoVR/assets/171096150/2f19fa77-c6a9-4e8f-96f1-6a92faade99a
somehow it also tries to get bugbait,and have multiply model errors 
Error loading resource file "models/weapons/v_pistol_stock.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_shroud.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_shroud_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_shroud_stock.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_shroud_stock_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper_no_shroud.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper_no_shroud_stock.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper_no_stock.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_pistol_hopper_no_stock_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_burst_grenade.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_burst_grenade_attached.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_burst.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_grenade.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_grenade_attached.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper_grenade_attached.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper_no_burst.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper_no_burst_grenade_attached.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper_no_grenade.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_shotgun_hopper_no_burst_grenade.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_holo.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_holo_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_casing.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_casing_ads.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_casing_no_holo.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_casing_no_holo_powerpack.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_smg1_powerpack.vmdl_c" (Error: ERROR_FILEOPEN)
Error loading resource file "models/weapons/v_grenade_novr.vmdl_c" (Error: ERROR_FILEOPEN)
HUDHearts startup sucessfully but its doesent works

**Comment by gb2dev** [comment]
Delete the file C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\game\hlvr\cfg\skill_manifest.cfg and the launcher will reinstall the mod.

**Comment by eawej** [comment]
> Delete the file C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\game\hlvr\cfg\skill_manifest.cfg and the launcher will reinstall the mod.

Deleted,but now launcher says
Download error: Error transferring https:// codeload.github.com/gb2dev/HLA-NoVR/zip/refs/heads/-main - server replied:
