### ISSUE TITLE
Impossible to release G-Man due to a possible script error

### ISSUE THREAD

**Issue by Scavenger6** [gb2dev/HLA-NoVR#247]
The whole game worked fine until I reached the G-Man's cage, the cables just move to it and then nothing happens except some error messages like "...common\Half-Life Alyx\game\hlvr\scripts\vscripts\novr.lua:2705: attempt to index global 'player' (a nil value)"
I'm really not good at scripting, but I think the problem is "**local player = Entities:GetLocalPlayer()**" at "**function GrabCandlers(a, b)**" in **novr.lua** is missing. At least it worked for me after I added this line.

**Comment by gb2dev** [comment]
Fixed
