### ISSUE TITLE
Strange blue shape at top middle of screen

### ISSUE THREAD

**Issue by VaughanG** [gb2dev/HLA-NoVR#248]
Playing on native resolution of 3440 X 1440 monitor.
![Screenshot](https://github.com/gb2dev/HLA-NoVR/assets/37030783/9ec13366-a847-4eba-a7d0-9272ebcbeb21)
I didn't see Alyx put on a baseball cap!
I know some people have been able to play at this resolution without problems. 
Any suggestions that may help?
Thanks,
VaughanG

**Comment by gb2dev** [comment]
You put on a hat. Press U to unequip it (you must have missed the tutorial tooltip)

**Comment by VaughanG** [comment]
That did the trick thank you muchly.
