### ISSUE TITLE
Instructions for Linux installation is inconsistent

### ISSUE THREAD

**Issue by magical-heyrovsky** [gb2dev/HLA-NoVR#251]
The [FAQ](https://docs.google.com/document/d/1mlDz24iE1r4Lf16y5N9I37ZIvm4V0ie2Sxg1GBlcs10) linked in https://github.com/gb2dev/HLA-NoVR?tab=readme-ov-file#installation has a section called _HOW DO I INSTALL THE MOD ON STEAM DECK/LINUX?_
which is not consistent what is said here https://github.com/gb2dev/HLA-NoVR-Launcher?tab=readme-ov-file#steam-decklinux.

It's not clear if the installation in the FAQ (with does not mention the launcher) is correct or if the launcher is the preferred option.

**Comment by gb2dev** [comment]
I updated the README
