### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by FlockersDesign** [gb2dev/HLA-NoVR#254]
There seems to be a huge issue with the performance

when the game runs fine i get over 150 to 200 FPS but every 2 minutes or less it drops as low are 24 FPS
and this is not just a one time things this seems to happen every time and again every 1 to 2 minuts but it can sometimes even be every 20 seconds 
this really needs to be fixed

**Comment by gb2dev** [comment]
I seriously doubt this is from the mod, VScript shouldn't affect game performance. Otherwise more people would have noticed

**Comment by FlockersDesign** [comment]
Well im pretty sure it is

Im running a intel i7 12700k RTX 3060 64GB of ram
And the game is on a kingston C3000 M.2
And when running the game in VR there are 0 problems

And aa a actual game developer
These aint reapondes you shut give
Bad jugemenr and directly pitting the problem on the player
Yea that is not the correct way

Best regards
E.Kranenburg
Flockers Design
