### ISSUE TITLE
BUG: It is impossible to pass through an open door.

### ISSUE THREAD

**Issue by chromKa** [gb2dev/HLA-NoVR#259]
Chapter 2 - Vortigaunt's safehouse.
I can't get through the door.

I met this problem at the very beginning game (Chapter 1), when we were coming down from the building, there was a door on the floor below, I opened it and I couldn't get through it. So far I haven't pressed the E button again, but now I have nothing to press, because Vortigaunt opens the door himself. I tried loading the save a little earlier - and it still didn't help.
![20240814165901_1](https://github.com/user-attachments/assets/4249bc9a-4762-46cb-8f92-0928a7a617de)

**Comment by DarkGradient** [comment]
A temporary solution is to look a little further than the door, and use the command - ent_teleport !player. it should help you
no sv_cheats need.

**Comment by chromKa** [comment]
> A temporary solution is to look a little further than the door, and use the command - ent_teleport !player. it should help you

I used "noclip" command in the console. It helped. But the problem needs to be solved
