### ISSUE TITLE
BUG: It is impossible to go any further

### ISSUE THREAD

**Issue by chromKa** [gb2dev/HLA-NoVR#261]
CHAPTER 11: The last scene.
In this place, a passage to the balcony opens, but it is not possible to pass, as well as in the [https://github.com/gb2dev/HLA-NoVR/issues/259](url) - an invisible wall. Only noclip helps. 
![20240818115319_1](https://github.com/user-attachments/assets/9bf13a35-3ec0-48ae-b7b3-c2432f261196)

P.S. In many places of the game, the character gets stuck or cannot pass if there are some objects on the ground. I think these problems are related.

**Comment by gb2dev** [comment]
Should be fixed, if not let me know (obviously you need a save from before this map)
