### ISSUE TITLE
Deadliest Catch not unlocking

### ISSUE THREAD

**Issue by Nerkie** [gb2dev/HLA-NoVR#263]
The grenades tend to fly way over my head, leaving me no opportunity to grab them. For the rare chance I do grab one, I have tried the following: throwing it away, throwing it back at them and killing them, throwing it at a different soldier and killing them, nothing so far is popping the achievement. It did say to report it here if you're not able to unlock one and well... here I am. I hope this can be resolved so I can continue carrying the gnome to the end, much appreciated!

**Comment by andrewostrin** [comment]
Confirming this. 
Deadliest Catch and Up in Arms don't unlock on Steam Deck manual install.

**Comment by Nerkie** [comment]
Interesting, because for me I installed via the launcher... but that's good to know. I know in VR you have to grab the grenade with your left hand, but whatever they did to make it unlock with no vr, I just can't seem to get it to unlock, no matter how many attempts or the location.

**Comment by berkaybakacak** [comment]
yep, same issue here. I caught the grenade over and over again, but the achievement didn't unlock. I think I was at the chapter 5 or 6

**Comment by gb2dev** [comment]
Yeah I will add this again today
