### ISSUE TITLE
how to play without launcher

### ISSUE THREAD

**Issue by Mitia514** [gb2dev/HLA-NoVR#274]
Hello everyone. I wanted to return to the game with this mod, but I don't need a launcher. I don't like the new game menu. I just want Alex's hand animation and a game menu to pause the game. Is it possible without using a launcher? I tried to install it, but every time I launch it, it takes a very long time to update (it takes an hour). When I launch the game, the menu is just awful (for some reason it's on the 2nd monitor, it's scary. Can I just download the mod from GitHub like before and copy it where I need it?

**Comment by gb2dev** [comment]
You can still install it manually (instructions for that were in older versions) and load a map through the console.
